services:
  server:
    image: chat-server
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - chat-network
    stdin_open: true
    tty: true

  mitm:
    image: chat-mitm
    container_name: mitm
    ports:
      - "8000:8000"
    networks:
      - chat-network
    stdin_open: true
    tty: true
    depends_on:
      - server

  client:
    image: chat-client
    container_name: client
    networks:
      - chat-network
    stdin_open: true
    tty: true
    depends_on:
      - mitm

networks:
  chat-network:
    driver: bridge