FROM ubuntu:24.04

RUN apt-get update && apt-get install -y gcc libssl-dev

WORKDIR /app

COPY server /app/server

RUN gcc server/server.c server/services.c server/users.c server/chat.c server/dh.c server/aes.c -o server/server -lcrypto

CMD ["./server/server"]