FROM ubuntu:24.04

RUN apt-get update && apt-get install -y gcc libssl-dev

WORKDIR /app

COPY client /app/client

RUN gcc client/client.c client/services.c client/dh.c client/aes.c -o client/client -lcrypto

CMD ["./client/client"]